[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.9.3",
    "scipy==1.14.1",
    "vpython==7.6.5",
]
